<p>&nbsp<span style="font-size: medium"><b>Por que adquirir VIP?</b></span></p>
<p><br />
<span style="color: rgb34, 34, 34 font-family: arial, sans-serif font-size: 13px">O Mind Freak &eacute gratuito e os jogadores s&atildeo bem-vindos para jogar por quanto tempo quiserem, livres de quaisquer cobran&ccedilas. Mesmo assim, se voc&ecirc gosta do jogo, voc&ecirc pode contribuir com o servidor e adquirir uma VIP Time para elevar suas experi&ecircncias a um patamar extraordin&aacuterio. Como um jogador VIP, voc&ecirc ter&aacute vantagens adicionais dentro do game. Adquira sua VIP Time para tornar o jogo ainda mais divertido!</span><br />
Os seguintes benef&iacutecios est&atildeo dispon&iacuteveis para jogadores VIP:</p>
<p style="margin-left: 40px"><img alt="" src="http://UnderWar.org/layouts/tibia/imagens/content/bullet.gif" /><b>Acesso &agraves &Aacutereas VIP!</b> <br />
<span style="color: rgb34, 34, 34 font-family: arial, sans-serif font-size: 13px">Acesso &agraves &Aacutereas VIP! Como um jogador VIP voc&ecirc pode navegar para as misteri&oacutesas ilhas Grendor. Explore enormes &aacutereas novas e dungeons que voc&ecirc nunca viu antes. Visite novas cidades! Lute com novas criaturas! Sendo um jogador VIP, voc&ecirc ter&aacute mais para ver e mais para fazer.</span></p>
<p style="margin-left: 40px"><img alt="" src="http://UnderWar.org/layouts/tibia/imagens/content/bullet.gif" /> <b>Sem filas!</b><br />
<span style="color: rgb34, 34, 34 font-family: arial, sans-serif font-size: 13px">Se o servidor atingir o seu limite de usu&aacuterios online, os jogadores enfrentar&atildeo filas para poder entrar no jogo. Como um jogador VIP, voc&ecirc ter&aacute prioridade no login. Diga adeus &agraves longas e exaustivas filas. Jogue quando quiser e a hora que quiser!</span></p>
<p style="margin-left: 40px"><img alt="" src="http://UnderWar.org/layouts/tibia/imagens/content/bullet.gif" /> <b>NPCs especiais!</b> <br />
<span style="color: rgb34, 34, 34 font-family: arial, sans-serif font-size: 13px">Alguns NPCs da &Aacuterea VIP oferecem descontos ou servi&ccedilos exclusivos. O Dark Rodo de Grendor vende runas como Magic Wall, Wild Growth e outras. A NPC Emilia compra o loot por um pre&ccedilo 10% mais caro e o NPC Bless oferece as 5 blessings aos jogadores VIP, que dispensa o uso do AoL!</span></p>
<p style="margin-left: 40px"><img alt="" src="http://UnderWar.org/layouts/tibia/imagens/content/bullet.gif" /> <b>Treinadores com DP!</b> <br />
<span style="color: rgb34, 34, 34 font-family: arial, sans-serif font-size: 13px">Voc&ecirc est&aacute cansado de procurar por treinadores livres? Est&aacute cansado de perder sua vaga para conseguir mais comida e muni&ccedil&atildeo? Jogadores VIP podem treinar a hora que quiserem e t&ecircm acesso ao seu Depot dentro da cabine de treinamento!</span></p>
<p style="margin-left: 40px"><img alt="" src="http://UnderWar.org/layouts/tibia/imagens/content/bullet.gif" /> <b>Maior capacidade da VIP List!</b> <br />
<span style="color: rgb34, 34, 34 font-family: arial, sans-serif font-size: 13px">Jogadores VIP t&ecircm 7x mais capacidade em suas VIP Lists. Adicione quantos amigos quiser!</span></p>
<p style="margin-left: 40px"><img alt="" src="http://UnderWar.org/layouts/tibia/imagens/content/bullet.gif" /> <b>Maior capacidade dos Depots!</b> <br />
<span style="color: rgb34, 34, 34 font-family: arial, sans-serif font-size: 13px">Jogadores VIP podem colocar quantos itens quiserem em seus Depots, sem grandes preocupa&ccedil&otildees com limites. Guarde at&eacute 5.000 items de forma segura! Isso se aplica apenas ao depot chest, n&atildeo ao Locker.</span></p>
<p style="margin-left: 40px"><img alt="" src="http://UnderWar.org/layouts/tibia/imagens/content/bullet.gif" /><b>&nbspBenef&iacutecios nas Rates VIPS!</b> <br />
<span style="color: rgb34, 34, 34 font-family: arial, sans-serif font-size: 13px">Jogadores VIP recebem mais loot do que jogadores frees, e em um evento de double loot, esse beneficio tamb&eacutem ser&aacute dobrado.</span></p>
<p><i> As regras s&atildeo v&aacutelidas para todos. Se um jogador VIP violar qualquer uma das regras do Mind Freak, poder&aacute ser banido ou at&eacute mesmo deletado do jogo.</i> <br />
<br />
Por favor note que esta n&atildeo &eacute uma lista exaustiva. Muitos outros benef&iacutecios n&atildeo est&atildeo listados. &Eacute poss&iacutevel que os atuais benef&iacutecios sejam alterados ou at&eacute mesmo eliminados no futuro. Adquira sua VIP Time hoje e aproveite o Mind Freak em sua melhor forma!</p>
